Psychotip_backend/Psychotip_backend/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.views.generic.base import RedirectView

import psychotip_admin.urls as psychotip_admin
import api.urls as api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urls)),
    url(r'^psychotip_admin/', include(psychotip_admin, namespace='psychotip_admin')),
    url(r'^$', RedirectView.as_view(url='psychotip_admin/', permanent='true'), name='index'),
]

Psychotip_backend/api/urls.py
from django.conf.urls import url
from . import views
app_name = 'api'

urlpatterns = [
    url(r'^create_user/$', views.UserCreate.as_view(), name='account_create'),
    url(r'^update_user/$', views.UserUpdate.as_view(), name='update_user'),
    url(r'^user_view/(?P<user_id>\w+)', views.UserView.as_view(), name='user_view'),
    url(r'^retrieve_quote/', views.RetrieveQuote.as_view(), name='retrieve_quote'),
    url(r'^psychologist_schedule/', views.PsychologistSchedule.as_view(), name='psychologist_schedule'),
    url(r'^view_schedule/(?P<user_id>\w+)', views.RetrieveSchedule.as_view(), name='view_schedule'),
    url(r'^delete_schedule/', views.DeleteSchedule.as_view(), name='delete_schedule'),
    url(r'^login_validate/$', views.UserValidationLogin.as_view(), name='login_validate'),
    url(r'^create_counseling/', views.CounselingSchedule.as_view(), name='create_counseling')
]

Psychotip_backend/psychotip_admin/urls.py
from django.conf.urls import url
from .views import *

app_name = 'psychotip_admin'

urlpatterns = [
    url(r'^login/', authenticate_login, name='authenticate_login'),
    url(r'^logout/', authenticate_logout, name='authenticate_logout'),
    url(r'^createqotd', create_qotd, name='create_qotd'),
    url(r'^qotd/qotdlist/', qotd_list, name='qotd_list'),
    url(r'^qotd/', quote_of_the_day, name='quote_of_the_day'),
    url(r'^$', index, name='index')
]

Psychotip_backend/psychotip_admin/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from api.models import Admin, User, Quotes

# Create your views here.
RESPONSE = {}

def index(request):
    if 'user_login' in request.session:
        html = 'dashboard_page.html'
    else:
        html = 'login_page.html'
    return render(request, html)

def authenticate_login(request):
    username = request.POST['username']
    password = request.POST['password']

    admin = Admin.objects.filter(username=username)
    if admin.count() != 0:
        user = User.objects.get(username=username)

        if password == user.password:
            request.session['user_login'] = username
            request.session['name'] = user.name
            messages.success(request, 'Login berhasil.')
        else:
            messages.error(request, 'Username atau password salah.')
    else:
        messages.error(request, 'User tidak ditemukan.')
    return HttpResponseRedirect(reverse('psychotip_admin:index'))


def authenticate_logout(request):
    request.session.flush()
    messages.info(request, 'Logout berhasil.')
    return HttpResponseRedirect(reverse('psychotip_admin:index'))

def quote_of_the_day(request):
    html = 'quote_of_the_day.html'
    return render(request, html)

@csrf_exempt
def create_qotd(request):
    konten = request.POST.get('quote', '')
    author = request.POST.get('author', '')

    if konten != '' and author != '':

        quote = Quotes(konten=konten, author=author)
        quote.save()

        messages.success(request, 'Quote berhasil ditambahkan.')

    elif konten == '' and author != '':
        messages.error(request, 'Konten quote tidak boleh kosong')

    elif konten != '' and author == '':
        messages.error(request, 'Author quote tidak boleh kosong')

    else:
        messages.error(request, 'Quote gagal ditambahkan. '
                                'Silahkan isi konten dan author untuk membuat quote.')

    return HttpResponseRedirect('qotd')

def qotd_list(request):
    quotes = Quotes.objects.all()
    RESPONSE['quotes'] = quotes
    html = 'quote_of_the_day_list.html'
    return render(request, html, RESPONSE)

Psychotip_backend/psychotip_admin/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>PsychoTip</title>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    {% block css %}

    {% endblock %}

    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <script src="{% static 'js/animate-in.js' %}"></script>
</head>
<body>
<header>
    {% include "partials/header.html" %}
</header>
<content>
    {% block content %}

    {% endblock %}
</content>
<footer>
    {% include "partials/footer.html" %}
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="{% static 'js/smooth-scroll.js' %}"></script>

{% block javascript %}

{% endblock %}

</body>

</html>

Psychotip_backend/psychotip_admin/templates/dashboard_page.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <div class="d-flex cover py-4">
        <div class="container">

            <ul class="breadcrumb px-0 mb-4">
                <li class="breadcrumb-item active"><b>Home</b></li>
            </ul>

            <div class="row">
                <div class="col-sm-12 col-md-4 mb-3 dash-title">

                    <h1 class="display-4 dash-text my-0">Dash —</h1>
                    <h1 class="display-4 dash-text">board.</h1>
                    <h1 class="full-dashboard-text">Dashboard.</h1>
                </div>
                <div class="col-sm-12 col-md-8">

                    <div class="card px-3 mb-4 shadow-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="{% comment %}col-sm-12{% endcomment %} col-3 align-items-center d-flex card-dash-pic pl-0">
                                    <img class="img-fluid d-block"
                                         src="{% static 'images/Dashboard - Admin/undraw_make_it_rain_iwk4 (1).svg' %}"
                                         alt="Pembayaran Psikolog">
                                </div>
                                <div class="col-7 align-items-center d-flex card-dash-text">

                                    <p class="text-primary my-0 card-dash-text-obj"><b>Pembayaran Psikolog</b></p>

                                </div>
                                <div class="col-2 align-items-center d-flex card-dash-arrow">
                                    <a class="link link--arrowed" href="#">
                                        <svg class="arrow-icon" xmlns="http://www.w3.org/2000/svg" width="32"
                                             height="32" viewBox="0 0 32 32">
                                            <g fill="none" stroke="#01C1C6" stroke-width="1.5" stroke-linejoin="round"
                                               stroke-miterlimit="10">
                                                <circle class="arrow-icon--circle" cx="16" cy="16" r="15.12"></circle>
                                                <path class="arrow-icon--arrow"
                                                      d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"></path>
                                            </g>
                                        </svg>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="card px-3 mb-4 shadow-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="{% comment %}col-sm-12{% endcomment %} col-3 align-items-center d-flex card-dash-pic pl-0">
                                    <img class="img-fluid d-block"
                                         src="{% static 'images/Dashboard - Admin/undraw_booking_33fn.svg' %}"
                                         alt="Pembayaran Psikolog">
                                </div>
                                <div class="col-7 align-items-center d-flex card-dash-text">

                                    <p class="text-primary my-0 card-dash-text-obj"><b>Jadwalkan Konseling</b></p>

                                </div>
                                <div class="col-2 align-items-center d-flex card-dash-arrow">
                                    <a class="link link--arrowed" href="#">
                                        <svg class="arrow-icon" xmlns="http://www.w3.org/2000/svg" width="32"
                                             height="32" viewBox="0 0 32 32">
                                            <g fill="none" stroke="#01C1C6" stroke-width="1.5" stroke-linejoin="round"
                                               stroke-miterlimit="10">
                                                <circle class="arrow-icon--circle" cx="16" cy="16" r="15.12"></circle>
                                                <path class="arrow-icon--arrow"
                                                      d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"></path>
                                            </g>
                                        </svg>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="card px-3 mb-4 shadow-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="{% comment %}col-sm-12{% endcomment %} col-3 align-items-center d-flex card-dash-pic pl-0">
                                    <img class="img-fluid d-block"
                                         src="{% static 'images/Dashboard - Pasien/undraw_events_2p66.svg' %}"
                                         alt="Pembayaran Psikolog">
                                </div>
                                <div class="col-7 align-items-center d-flex card-dash-text">

                                    <p class="text-primary my-0 card-dash-text-obj"><b>Tambahkan Acara</b></p>

                                </div>
                                <div class="col-2 align-items-center d-flex card-dash-arrow">
                                    <a class="link link--arrowed" href="#">
                                        <svg class="arrow-icon" xmlns="http://www.w3.org/2000/svg" width="32"
                                             height="32" viewBox="0 0 32 32">
                                            <g fill="none" stroke="#01C1C6" stroke-width="1.5" stroke-linejoin="round"
                                               stroke-miterlimit="10">
                                                <circle class="arrow-icon--circle" cx="16" cy="16" r="15.12"></circle>
                                                <path class="arrow-icon--arrow"
                                                      d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"></path>
                                            </g>
                                        </svg>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="card px-3 mb-4 shadow-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="{% comment %}col-sm-12{% endcomment %} col-3 align-items-center d-flex card-dash-pic pl-0">
                                    <img class="img-fluid d-block"
                                         src="{% static 'images/Dashboard - Pasien/undraw_to_do_list_a49b.svg' %}"
                                         alt="Pembayaran Psikolog">
                                </div>
                                <div class="col-7 align-items-center d-flex card-dash-text">

                                    <p class="text-primary my-0 card-dash-text-obj"><b>Buat Artikel</b></p>

                                </div>
                                <div class="col-2 align-items-center d-flex card-dash-arrow">
                                    <a class="link link--arrowed" href="#">
                                        <svg class="arrow-icon" xmlns="http://www.w3.org/2000/svg" width="32"
                                             height="32" viewBox="0 0 32 32">
                                            <g fill="none" stroke="#01C1C6" stroke-width="1.5" stroke-linejoin="round"
                                               stroke-miterlimit="10">
                                                <circle class="arrow-icon--circle" cx="16" cy="16" r="15.12"></circle>
                                                <path class="arrow-icon--arrow"
                                                      d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"></path>
                                            </g>
                                        </svg>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="card px-3 mb-4 shadow-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="{% comment %}col-sm-12{% endcomment %} col-3 align-items-center d-flex card-dash-pic pl-0">
                                    <img class="img-fluid d-block"
                                         src="{% static 'images/Dashboard - Admin/undraw_book_lover_mkck.svg' %}"
                                         alt="Pembayaran Psikolog">
                                </div>
                                <div class="col-7 align-items-center d-flex card-dash-text">

                                    <p class="text-primary my-0 card-dash-text-obj"><b>Tambah Kutipan</b></p>

                                </div>
                                <div class="col-2 align-items-center d-flex card-dash-arrow">
                                    <a class="link link--arrowed" href="{% url 'psychotip_admin:quote_of_the_day' %}">
                                        <svg class="arrow-icon" xmlns="http://www.w3.org/2000/svg" width="32"
                                             height="32" viewBox="0 0 32 32">
                                            <g fill="none" stroke="#01C1C6" stroke-width="1.5" stroke-linejoin="round"
                                               stroke-miterlimit="10">
                                                <circle class="arrow-icon--circle" cx="16" cy="16" r="15.12"></circle>
                                                <path class="arrow-icon--arrow"
                                                      d="M16.14 9.93L22.21 16l-6.07 6.07M8.23 16h13.98"></path>
                                            </g>
                                        </svg>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Footer -->

{% endblock %}

{% block javascript %}
    <script>

        $(document).ready(function () {

            if ($(window).width() < 992) {
                $(".dash-text").removeClass("display-4").addClass("display-5");
            }

            if ($(window).width() < 768) {
                $(".dash-title").addClass("text-center");

                $(".card-dash-pic").addClass("justify-content-center my-2");
                $(".card-dash-text").addClass("justify-content-center my-2");
                $(".card-dash-arrow").addClass("justify-content-center my-2");
            }

        });

        $(window).on('resize', function () {

            if ($(window).width() < 992) {
                $(".dash-text").removeClass("display-4").addClass("display-5");
            } else {
                $(".dash-text").removeClass("display-5").addClass("display-4");
            }

            if ($(window).width() < 768) {
                $(".dash-title").addClass("text-center");

                $(".card-dash-pic").addClass("justify-content-center my-2");
                $(".card-dash-text").addClass("justify-content-center my-2");
                $(".card-dash-arrow").addClass("justify-content-center my-2");
            } else {
                $(".dash-title").removeClass("text-center");

                $(".card-dash-pic").removeClass("justify-content-center my-2");
                $(".card-dash-text").removeClass("justify-content-center my-2");
                $(".card-dash-arrow").removeClass("justify-content-center my-2");
            }
        });

    </script>
{% endblock %}

Psychotip_backend/psychotip_admin/templates/quote_of_the_day.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <div class="d-flex cover py-4">
        <div class="container">

            <ul class="breadcrumb px-0 mb-4">
                <li class="breadcrumb-item"><a href="{% url 'psychotip_admin:index' %}"><b>Home</b></a></li>
                <li class="breadcrumb-item active"><b>Tambah Quote of the Day</b></li>
            </ul>

            <div class="row">
                <div class="col-sm-12 col-md-4 mb-3 dash-title">

                    <h1 class="display-4 dash-text my-0">Quote of</h1>
                    <h1 class="display-4 dash-text mb-3">the Day.</h1>
                    <img class="dash-text mb-3"
                         src="{% static 'images/Dashboard - Admin/undraw_book_lover_mkck.svg' %}"
                         alt="Pembayaran Psikolog">

                    <a class="link-underline-text-big link-underline" href="{% url 'psychotip_admin:qotd_list' %}">Lihat
                        Daftar Kutipan</a>


                    <h1 class="full-dashboard-text">Quote of the Day.</h1>
                </div>
                <div class="col-sm-12 col-md-8">
                    <form class="quote-of-the-day px-3" action="{% url 'psychotip_admin:create_qotd' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group mb-4">
                            <label for="kutipan">Kutipan</label>
                            <textarea class="form-control" id="quote" name="quote" rows="5"
                                      placeholder="Tulis kutipan disini."></textarea>
                        </div>
                        <div class="form-group mb-4">
                            <label for="exampleInputEmail1">Penulis</label>
                            <input type="text" class="form-control" id="author" name="author"
                                   placeholder="Tulis nama penulis disini.">
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">
                                SUBMIT
                            </button>
                        </div>
                    </form>
                    <div class="text-center mt-4">
                        <a class="link-underline-text-small link-underline"
                           href="{% url 'psychotip_admin:qotd_list' %}">Lihat Daftar Kutipan</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Footer -->

{% endblock %}

{% block javascript %}
    <script>

        $(document).ready(function () {

            if ($(window).width() < 992) {
                $(".dash-text").removeClass("display-4").addClass("display-5");
            }

            if ($(window).width() < 768) {
                $(".dash-title").addClass("text-center");

                $(".card-dash-pic").addClass("justify-content-center my-2");
                $(".card-dash-text").addClass("justify-content-center my-2");
                $(".card-dash-arrow").addClass("justify-content-center my-2");
            }

        });

        $(window).on('resize', function () {

            if ($(window).width() < 992) {
                $(".dash-text").removeClass("display-4").addClass("display-5");
            } else {
                $(".dash-text").removeClass("display-5").addClass("display-4");
            }

            if ($(window).width() < 768) {
                $(".dash-title").addClass("text-center");

                $(".card-dash-pic").addClass("justify-content-center my-2");
                $(".card-dash-text").addClass("justify-content-center my-2");
                $(".card-dash-arrow").addClass("justify-content-center my-2");
            } else {
                $(".dash-title").removeClass("text-center");

                $(".card-dash-pic").removeClass("justify-content-center my-2");
                $(".card-dash-text").removeClass("justify-content-center my-2");
                $(".card-dash-arrow").removeClass("justify-content-center my-2");
            }
        });

    </script>
{% endblock %}

Psychotip_backend/psychotip_admin/templates/quote_of_the_day_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <div class="d-flex cover py-4">
        <div class="container">

            <ul class="breadcrumb px-0 mb-4">
                <li class="breadcrumb-item"><a href="{% url 'psychotip_admin:index' %}"><b>Home</b></a></li>
                <li class="breadcrumb-item"><a href="{% url 'psychotip_admin:quote_of_the_day' %}"><b>Tambah Quote of the Day</b></a></li>
                <li class="breadcrumb-item active"><b>Daftar Kutipan</b></li>
            </ul>

            <div class="row">
                <div class="col-sm-12 col-md-4 mb-3 dash-title">

                    <h1 class="display-4 dash-text my-0">Quote of</h1>
                    <h1 class="display-4 dash-text mb-3">the Day.</h1>
                    <img class="dash-text"
                         src="{% static 'images/Dashboard - Admin/undraw_book_lover_mkck.svg' %}"
                         alt="Pembayaran Psikolog">
                    <h1 class="full-dashboard-text">Quote of the Day.</h1>
                </div>
                <div class="col-sm-12 col-md-8">
                    <div class="list-group">

                        {% for i in quotes %}

                            <div class="list-group-item flex-column align-items-start">
                                <p class="mb-1 text-primary"> {{ i.konten }} </p>
                                <small> {{ i.author }} </small>
                            </div>

                        {% endfor %}

                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Footer -->

{% endblock %}

{% block javascript %}
    <script>

        $(document).ready(function () {

            if ($(window).width() < 992) {
                $(".dash-text").removeClass("display-4").addClass("display-5");
            }

            if ($(window).width() < 768) {
                $(".dash-title").addClass("text-center");

                $(".card-dash-pic").addClass("justify-content-center my-2");
                $(".card-dash-text").addClass("justify-content-center my-2");
                $(".card-dash-arrow").addClass("justify-content-center my-2");
            }

        });

        $(window).on('resize', function () {

            if ($(window).width() < 992) {
                $(".dash-text").removeClass("display-4").addClass("display-5");
            } else {
                $(".dash-text").removeClass("display-5").addClass("display-4");
            }

            if ($(window).width() < 768) {
                $(".dash-title").addClass("text-center");

                $(".card-dash-pic").addClass("justify-content-center my-2");
                $(".card-dash-text").addClass("justify-content-center my-2");
                $(".card-dash-arrow").addClass("justify-content-center my-2");
            } else {
                $(".dash-title").removeClass("text-center");

                $(".card-dash-pic").removeClass("justify-content-center my-2");
                $(".card-dash-text").removeClass("justify-content-center my-2");
                $(".card-dash-arrow").removeClass("justify-content-center my-2");
            }
        });

    </script>
{% endblock %}