Psychotip_backend/Psychotip_backend/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.views.generic.base import RedirectView

import psychotip_admin.urls as psychotip_admin
import api.urls as api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urls)),
    url(r'^psychotip_admin/', include(psychotip_admin, namespace='psychotip_admin')),
    url(r'^$', RedirectView.as_view(url='psychotip_admin/', permanent='true'), name='index'),
]

Psychotip_backend/api/urls.py
from django.conf.urls import url
from . import views
app_name = 'api'

urlpatterns = [
    url(r'^create_user/$', views.UserCreate.as_view(), name='account_create'),
    url(r'^update_user/$', views.UserUpdate.as_view(), name='update_user'),
    url(r'^user_view/(?P<user_id>\w+)', views.UserView.as_view(), name='user_view'),
    url(r'^retrieve_quote/', views.RetrieveQuote.as_view(), name='retrieve_quote'),
    url(r'^psychologist_schedule/', views.PsychologistSchedule.as_view(), name='psychologist_schedule'),
    url(r'^view_schedule/(?P<user_id>\w+)', views.RetrieveSchedule.as_view(), name='view_schedule'),
    url(r'^delete_schedule/', views.DeleteSchedule.as_view(), name='delete_schedule'),
    url(r'^login_validate/$', views.UserValidationLogin.as_view(), name='login_validate'),
    url(r'^create_counseling/', views.CounselingSchedule.as_view(), name='create_counseling')
]

Psychotip_backend/psychotip_admin/urls.py
from django.conf.urls import url
from .views import *

app_name = 'psychotip_admin'

urlpatterns = [
    url(r'^login/', authenticate_login, name='authenticate_login'),
    url(r'^logout/', authenticate_logout, name='authenticate_logout'),
    url(r'^createqotd', create_qotd, name='create_qotd'),
    url(r'^qotd/qotdlist/', qotd_list, name='qotd_list'),
    url(r'^qotd/', quote_of_the_day, name='quote_of_the_day'),
    url(r'^$', index, name='index')
]

Psychotip_backend/psychotip_admin/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from api.models import Admin, User, Quotes

# Create your views here.
RESPONSE = {}

def index(request):
    if 'user_login' in request.session:
        html = 'dashboard_page.html'
    else:
        html = 'login_page.html'
    return render(request, html)

def authenticate_login(request):
    username = request.POST['username']
    password = request.POST['password']

    admin = Admin.objects.filter(username=username)
    if admin.count() != 0:
        user = User.objects.get(username=username)

        if password == user.password:
            request.session['user_login'] = username
            request.session['name'] = user.name
            messages.success(request, 'Login berhasil.')
        else:
            messages.error(request, 'Username atau password salah.')
    else:
        messages.error(request, 'User tidak ditemukan.')
    return HttpResponseRedirect(reverse('psychotip_admin:index'))


def authenticate_logout(request):
    request.session.flush()
    messages.info(request, 'Logout berhasil.')
    return HttpResponseRedirect(reverse('psychotip_admin:index'))

def quote_of_the_day(request):
    html = 'quote_of_the_day.html'
    return render(request, html)

@csrf_exempt
def create_qotd(request):
    konten = request.POST.get('quote', '')
    author = request.POST.get('author', '')

    if konten != '' and author != '':

        quote = Quotes(konten=konten, author=author)
        quote.save()

        messages.success(request, 'Quote berhasil ditambahkan.')

    elif konten == '' and author != '':
        messages.error(request, 'Konten quote tidak boleh kosong')

    elif konten != '' and author == '':
        messages.error(request, 'Author quote tidak boleh kosong')

    else:
        messages.error(request, 'Quote gagal ditambahkan. '
                                'Silahkan isi konten dan author untuk membuat quote.')

    return HttpResponseRedirect('qotd')

def qotd_list(request):
    quotes = Quotes.objects.all()
    RESPONSE['quotes'] = quotes
    html = 'quote_of_the_day_list.html'
    return render(request, html, RESPONSE)

Psychotip_backend/psychotip_admin/templates/partials/footer.html
{% comment %}
<div class="text-center bg-dark pt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 p-3">
                <h2 class="mb-4">Contact</h2>
                <p class="m-0">
                    <a href="tel:+246 - 542 550 5462" class="text-white">+246 - 542 550 5462</a>
                </p>
                <p>
                    <a href="mailto:info@pingendo.com" class="text-white">info@pingendo.com</a>
                </p>
            </div>
            <div class="col-md-4 p-3">
                <h2 class="mb-4">Location</h2>
                <p>
                    <a href="https://www.google.it/maps" target="blank" class="text-white">23 Fake Street <br>Seattle,
                        WA 00000</a>
                </p>
            </div>
            <div class="col-md-4 p-3">
                <h2 class="mb-4">Openings</h2>
                <p>11:00 - 15:00 &amp; 19:00 - 00:00 Tue/Fri <br>11:00 - 15:00 &amp; 19:00 - 02:00 Sat/Sun</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mt-3">
                <p class="text-center text-muted">© Copyright 2018 Pingendo - All rights reserved. </p>
            </div>
        </div>
    </div>
</div>{% endcomment %}

Psychotip_backend/psychotip_admin/templates/partials/header.html
{% comment %}
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <div class="container"><a class="navbar-brand text-primary" href="#">
        <b class="text-weight-heavy">PsychoTip</b>
    </a>
        <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                data-target="#">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar5">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="#">Daftar Penjual</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Daftar Transaksi</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link text-primary text-weight-bold" href="#">Profil</a></li>
                <form id="logout-form" action="#" method="post">
                    {% csrf_token %}
                    <a id="logout-btn" class="nav-item nav-link">Logout</a>
                </form>
            </ul>
        </div>
    </div>
</nav>{% endcomment %}

<nav class="navbar navbar-expand-md navbar-light bg-white">
    <div class="container"><a class="navbar-brand mx-0" href="{% url 'psychotip_admin:index' %}">
        <b class="text-primary">PsychoTip</b>
    </a>
        <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                data-target="#navbarlink">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse nav-dir" id="navbarlink">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-2"><a class="nav-link text-primary" href="#"><i class="far fa-bell"></i></a></li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item nav-log">
                    {% comment %}{% if user.is_authenticated %}
                        <p>Welcome, <b>{{ user }}</b>. <a href="{% url 'logout' %}">Logout</a></p>
                    {% else %}{% endcomment %}
                        <a class="btn btn-primary btn-header" href="{% url 'psychotip_admin:authenticate_logout' %}">LOGOUT</a>
                    {% comment %}{% endif %}{% endcomment %}
                </li>
            </ul>
        </div>
    </div>
</nav>